
global.size=12;
global.kadr_at_krit=28;
global.st=m_object_st_spr
global.at=m_object_at_spr
global.wl=hero_wl_spr;
global.kadrs_st=60;
global.kadrs_at=60;
global.kadrs_dt=36;
global.mat_count = 1;
global.xw=x;
global.xh=y;
global.e_name="Ogre";
global.e_hp=500;
global.e_max_hp=global.e_hp;
global.e_attack=14;
global.e_armor=2;
global.e_kd=4;
global.e_award=100;
global.e_mnog=1;
global.e_speed = 0.4;
global.main_substring = string_delete(object_get_name(object_index), string_length(object_get_name(object_index))-2, 4)
global.d_red = 0;
global.d_green = 0.5;
global.d_blue = 1.0;
global.reg_rad = 22
global.e_speed_attack = 1;
global.e_name_offset = 0;
direction-=180
alarm[0]=100
